-- ============================================================================
-- Seed: 100 Millennials (8x) songs for the emotion-classification pilot.
--
-- Run AFTER 20250102000000_emotion_classification.sql.
-- Source of truth: docs/seed-catalog-millennial.md
-- Safe to re-run: the unique index on (title, artist) makes this an upsert.
--
-- No lyrics are stored - only title / artist / year / generation.
-- ============================================================================

insert into public.catalog_songs (title, artist, year, generation_id, source) values
  ('Tình Thôi Xót Xa',              'Lam Trường',       1997, 'millennial', 'manual'),
  ('Mưa Phi Trường',                'Lam Trường',       2000, 'millennial', 'manual'),
  ('Tình Khúc Vàng',                'Đan Trường',       1999, 'millennial', 'manual'),
  ('Kiếp Ve Sầu',                   'Đan Trường',       1999, 'millennial', 'manual'),
  ('Vầng Trăng Cô Đơn',             'Đan Trường',       2001, 'millennial', 'manual'),
  ('Cô Gái Mở Đường',               'Phương Thanh',     1999, 'millennial', 'manual'),
  ('Giã Từ Trái Tim',               'Phương Thanh',     2001, 'millennial', 'manual'),
  ('Hãy Yêu Nhau Đi',               'Phương Thanh',     2001, 'millennial', 'manual'),
  ('Một Người Đi',                  'Cẩm Ly',           2000, 'millennial', 'manual'),
  ('Nếu Anh Là Người Đó',           'Cẩm Ly',           2001, 'millennial', 'manual'),
  ('Chuyện Tình Lan Và Điệp',       'Cẩm Ly',           2002, 'millennial', 'manual'),
  ('Dẫu Có Mong Manh',              'Mỹ Tâm',           2001, 'millennial', 'manual'),
  ('Họa Mi Tóc Nâu',                'Mỹ Tâm',           2002, 'millennial', 'manual'),
  ('Ước Gì',                        'Mỹ Tâm',           2002, 'millennial', 'manual'),
  ('Tóc Nâu Môi Trầm',              'Mỹ Tâm',           2003, 'millennial', 'manual'),
  ('Nhé Anh',                       'Mỹ Tâm',           2004, 'millennial', 'manual'),
  ('Quên Cách Yêu',                 'Ưng Hoàng Phúc',   2004, 'millennial', 'manual'),
  ('Thà Rằng Như Thế',              'Ưng Hoàng Phúc',   2003, 'millennial', 'manual'),
  ('Mộng Uyên Ương Hồ Điệp',        'Ưng Hoàng Phúc',   2005, 'millennial', 'manual'),
  ('Vầng Trăng Khóc',               'Khánh Phương',     2005, 'millennial', 'manual'),
  ('Bởi Vì Anh Yêu Em',             'Quang Vinh',       2001, 'millennial', 'manual'),
  ('Tình Yêu Tôi Hát',              'Quang Vinh',       2002, 'millennial', 'manual'),
  ('Chàng Trai Si Tình',            'Quang Vinh',       2004, 'millennial', 'manual'),
  ('Mưa Tình Yêu',                  'Thanh Thảo',       2003, 'millennial', 'manual'),
  ('Đèn Đỏ',                        'Thanh Thảo',       2004, 'millennial', 'manual'),
  ('Ngỡ Như Là Mơ',                 'Ngọc Sơn',         2003, 'millennial', 'manual'),
  ('Hát Cho Người Ở Lại',           'Ngọc Sơn',         2005, 'millennial', 'manual'),
  ('Lạc Mất Mùa Xuân',              'Khánh Ly',         1998, 'millennial', 'manual'),
  ('Cát Bụi',                       'Trịnh Công Sơn',   1999, 'millennial', 'manual'),
  ('Diễm Xưa',                      'Khánh Ly',         2000, 'millennial', 'manual'),
  ('Biển Nhớ',                      'Khánh Ly',         2001, 'millennial', 'manual'),
  ('Như Cánh Vạc Bay',              'Hồng Nhung',       2000, 'millennial', 'manual'),
  ('Hạ Trắng',                      'Hồng Nhung',       2001, 'millennial', 'manual'),
  ('Ru Ta Ngậm Ngùi',               'Hồng Nhung',       2002, 'millennial', 'manual'),
  ('Ngẫu Nhiên',                    'Trịnh Công Sơn',   2003, 'millennial', 'manual'),
  ('Một Cõi Đi Về',                 'Trịnh Công Sơn',   2004, 'millennial', 'manual'),
  ('Tôi Ơi Đừng Tuyệt Vọng',        'Trịnh Công Sơn',   2005, 'millennial', 'manual'),
  ('Quê Hương',                     'Quang Lê',         2002, 'millennial', 'manual'),
  ('Sương Trắng Miền Quê Ngoại',    'Quang Lê',         2003, 'millennial', 'manual'),
  ('Đau Xót Lý Con Cua',            'Quang Lê',         2004, 'millennial', 'manual'),
  ('Người Ở Lại Xóm Núi',           'Quang Lê',         2005, 'millennial', 'manual'),
  ('Gánh Hàng Rong',                'Hoài Linh',        2003, 'millennial', 'manual'),
  ('Bèo Dạt Mây Trôi',              'Mỹ Linh',          2001, 'millennial', 'manual'),
  ('Áo Lụa Hà Đông',                'Mỹ Linh',          2002, 'millennial', 'manual'),
  ('Tóc Dài',                       'Mỹ Linh',          2003, 'millennial', 'manual'),
  ('Lua Vàng Sợi Nhớ',              'Cẩm Ly',           2004, 'millennial', 'manual'),
  ('Đêm Cuối',                      'Nguyễn Hưng',      2002, 'millennial', 'manual'),
  ('Khúc Tình Xưa',                 'Nguyễn Hưng',      2003, 'millennial', 'manual'),
  ('Thành Phố Mưa Bay',             'Đàm Vĩnh Hưng',    2003, 'millennial', 'manual'),
  ('Tình Yêu Còn Mãi',              'Đàm Vĩnh Hưng',    2004, 'millennial', 'manual'),
  ('Biết Ơn Anh',                   'Bảo Thy',          2007, 'millennial', 'manual'),
  ('Lạc Rối',                       'Bảo Thy',          2008, 'millennial', 'manual'),
  ('Hạnh Phúc Khi Có Anh',          'Bảo Thy',          2009, 'millennial', 'manual'),
  ('Cơn Mưa Tình Yêu',              'Bảo Thy',          2009, 'millennial', 'manual'),
  ('Vòng Tay Ấm',                   'Đông Nhi',         2008, 'millennial', 'manual'),
  ('Chàng Baby',                    'Đông Nhi',         2009, 'millennial', 'manual'),
  ('Chuyện Của Mùa Đông',           'Đông Nhi',         2010, 'millennial', 'manual'),
  ('Thứ Tha',                       'Đông Nhi',         2010, 'millennial', 'manual'),
  ('Đừng Hỏi Vì Sao',               'Lương Bích Hữu',   2006, 'millennial', 'manual'),
  ('Cô Gái Trung Hoa',              'Lương Bích Hữu',   2007, 'millennial', 'manual'),
  ('Dù Tình Phai',                  'Lương Bích Hữu',   2008, 'millennial', 'manual'),
  ('Vẫn Mãi Yêu Em',                'Khổng Tú Quỳnh',   2008, 'millennial', 'manual'),
  ('Yêu Thương Mong Manh',          'Khổng Tú Quỳnh',   2009, 'millennial', 'manual'),
  ('Đôi Mắt',                       'Wanbi Tuấn Anh',   2005, 'millennial', 'manual'),
  ('Vì Anh',                        'Wanbi Tuấn Anh',   2007, 'millennial', 'manual'),
  ('Mắt Em',                        'Ngọc Khuê',        2006, 'millennial', 'manual'),
  ('Nỗi Nhớ Thôi',                  'Khánh Phương',     2006, 'millennial', 'manual'),
  ('Tình Yêu Chắp Vá',              'Khánh Phương',     2007, 'millennial', 'manual'),
  ('Nhớ Lắm',                       'Xuân Mai',         2004, 'millennial', 'manual'),
  ('Đêm Tình Nhân',                 'Đàm Vĩnh Hưng',    2005, 'millennial', 'manual'),
  ('Vùng Lá Me',                    'Vũ Khanh',         2003, 'millennial', 'manual'),
  ('Tình Nghĩa Đôi Ta Chỉ Thế Thôi','Đàm Vĩnh Hưng',    2006, 'millennial', 'manual'),
  ('Mong Manh Tình Về',             'Lam Trường',       2002, 'millennial', 'manual'),
  ('Cho Vừa Lòng Nhau',             'Lam Trường',       2003, 'millennial', 'manual'),
  ('Dòng Máu Lạc Hồng',             'Ngọc Sơn',         2004, 'millennial', 'manual'),
  ('Người Phương Nam',              'Quang Lê',         2006, 'millennial', 'manual'),
  ('Yêu Vội',                       'Khổng Tú Quỳnh',   2010, 'millennial', 'manual'),
  ('Khi Xưa Ta Bé',                 'Khắc Việt',        2010, 'millennial', 'manual'),
  ('Một Mình',                      'Khắc Việt',        2011, 'millennial', 'manual'),
  ('Cơn Mưa Ngang Qua',             'Tiên Tiên',        2012, 'millennial', 'manual'),
  ('Những Ngày Vắng Em',            'Nam Cường',        2008, 'millennial', 'manual'),
  ('Bay Giữa Ngân Hà',              'Nam Cường',        2008, 'millennial', 'manual'),
  ('Bầu Trời Của Em',               'Hồ Ngọc Hà',       2007, 'millennial', 'manual'),
  ('Xin Anh Anh Đừng',              'Hồ Ngọc Hà',       2008, 'millennial', 'manual'),
  ('Nếu Như Anh Đến',               'Văn Mai Hương',    2011, 'millennial', 'manual'),
  ('Yêu Anh',                       'Cao Thái Sơn',     2009, 'millennial', 'manual'),
  ('Con Đường Mưa',                 'Cao Thái Sơn',     2010, 'millennial', 'manual'),
  ('Biết Yêu',                      'Bảo Anh',          2012, 'millennial', 'manual'),
  ('Anh Vẫn Hi Vọng',               'Bảo Anh',          2013, 'millennial', 'manual'),
  ('Vội Vàng',                      'Phạm Trưởng',      2011, 'millennial', 'manual'),
  ('Nhớ Người Hay Nhớ',             'Hoàng Thùy Linh',  2011, 'millennial', 'manual'),
  ('Rơi',                           'Hoàng Thùy Linh',  2012, 'millennial', 'manual'),
  ('Cảm Giác Khi Được Yêu',         'Khắc Việt',        2012, 'millennial', 'manual'),
  ('Mãi Mãi Bên Nhau',              'Noo Phước Thịnh',  2010, 'millennial', 'manual'),
  ('Chỉ Riêng Mình Anh',            'Noo Phước Thịnh',  2011, 'millennial', 'manual'),
  ('Ánh Nắng Của Anh',              'Đăng Khôi',        2008, 'millennial', 'manual'),
  ('Nép Vào Gió',                   'Hoàng Hải',        2009, 'millennial', 'manual'),
  ('Giấc Mơ Trưa',                  'Hoàng Hải',        2010, 'millennial', 'manual'),
  ('Mưa',                           'Tuấn Hưng',        2004, 'millennial', 'manual'),
  ('Vẫn Là Em',                     'Tuấn Hưng',        2006, 'millennial', 'manual')
on conflict (lower(title), lower(artist)) do update set
  year = excluded.year,
  generation_id = excluded.generation_id;
